### ISSUE TITLE
About AcEM in the paper

### ISSUE THREAD

**Issue by kerkathy** [xfactlab/emnlp2023-damaging-retrieval#1]
Hi,

Thanks for sharing the code for this paper, as I'm also interested in the problem of what context to put as prompt in RAG system, I found this paper really inspiring, especially the analysis.

Just got a little question here. In Fig. 2 you drew the curve of EM and AcEM, although it's written that AcEM is to measure _the model’s performance when paired with gold evidence_, I still didn't get it. How does EM different from AcEM?
Considering the case of three context, do we put three negative passages as context when computing EM; on the other hand put "gold passage + three negative passage" as context when computing AcEM?

Plus, will you also share the code for the pilot study section in the paper?

Tks!

**Comment by philhoonoh** [comment]
Sorry for the late response.

Regarding your first question:
You can think of AcEM(K) as the accumulated score of EM(N), where N ranges from 1 to K. Essentially, AcEM(K) = 1 if any one of the EM(N) = 1. 
`AcEM@k is the maximum of
all EM@k values up to k. For instance, AcEM@k
equals 1 if at least one of the values in (EM@1,
EM@2, ..., EM@k) equals 1. `
This approach can be applied to retrieved contexts as well where there is no guarantee of the existence of gold context. For further details, check sec4.

In the experimental setting for Figure 2, we use "gold passage + N negative passages," so an increase in AcEM indicates that some negative passages can actually help generate the correct answer.

For your second question:
I'm confident you can implement the code using the provided data!

Best regards,
